name: Android CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Define the environment (Linux in this case)

    steps:
      # Step 1: Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17 (required to build Android apps)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Change permission of the gradlew script
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Step 4: Cache Gradle dependencies to speed up the build process
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # Step 5: Build the Android app using Gradle
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Step 6: Run unit tests if they exist
      - name: Run Unit Tests
        run: ./gradlew test

      # Step 7: Upload the built APK as a GitHub Action artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
